name: Publish to NuGet

on:
  push:
    tags-ignore:
      - testing_*

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v7
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release -p:Version='${{ github.ref_name }}' Unscrambler/Unscrambler.csproj
      - name: Pack
        run: dotnet pack --no-build --configuration Release -p:Version='${{ github.ref_name }}' --output artifacts Unscrambler/Unscrambler.csproj
      - name: NuGet login
        id: nuget-login
        uses: NuGet/login@v1
        with:
          user: perchbird
      - name: Publish to NuGet
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate